logging:
  level:
    org.springframework.web: ERROR
    pl.coderstrust: INFO

  file: ./accountant.log

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: adam.nowak.coder@gmail.com
    password: adamnowak123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

#  datasource:
#    url: jdbc:mysql://localhost:3306/accounting_system?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
#    username: root
#    password: hyber!123
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    continueOnError: true
#    initialize: false
#    initialSize: 0
#    timeBetweenEvictionRunsMillis: 5000
#    minEvictableIdleTimeMillis: 5000

active:
  database: memory